# Generated by Django 5.1.1 on 2024-09-09 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_customer_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='testusers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phonenumber', models.CharField(max_length=200)),
                ('password', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
