# Generated by Django 5.1.1 on 2024-09-14 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_delete_customer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Drug",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("drug_name", models.CharField(max_length=255)),
                ("drug_company", models.CharField(max_length=255)),
                ("drug_quantity", models.IntegerField()),
                ("drug_code", models.CharField(max_length=255)),
            ],
        ),
    ]
